package se.mickevi.boctor;

public enum ItemSlots {
    WEAPON_ANY_HAND,
    WEAPON_2_HAND,
    WEAPON_PRIMARY_HAND,
    WEAPON_OFF_HAND,
    WEAPON_PRIMARY_FOOT,
    WEAPON_OFF_FOOT,
    ARMOR_HEAD,
    ARMOR_BODY,
    ARMOR_HANDS,
    ARMOR_ARMS,
    ARMOR_LEGS,
    ARMOR_FEET,
    ARMOR_RING1,
    ARMOR_RING2,
    ARMOR_NECKLACE


}
